import 'package:flutter/material.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel23widget/generated/GeneratedNameWidget.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel23widget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel23widget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel23widget/generated/GeneratedEmailWidget.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel23widget/generated/GeneratedRectangle3Widget1.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel23widget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel23widget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel23widget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel23widget/generated/GeneratedMobileNumberWidget.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel23widget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel23widget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel23widget/generated/GeneratedArrow1Widget.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel23widget/generated/GeneratedRegisterWidget.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel23widget/generated/GeneratedArrow2Widget.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel23widget/generated/GeneratedSaviorWidget1.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel23widget/generated/GeneratedConfirmPasswordWidget.dart';

/* Frame Google Pixel 2 - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGooglePixel23Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 93, 7, 133),
                ),
              ),
              Positioned(
                left: 111.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 192.0,
                height: 94.0,
                child: GeneratedSaviorWidget1(),
              ),
              Positioned(
                left: 95.0,
                top: 265.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 39.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: 96.0,
                top: 409.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 39.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 95.0,
                top: 337.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 39.0,
                child: GeneratedRectangle3Widget1(),
              ),
              Positioned(
                left: 95.0,
                top: 312.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 23.0,
                child: GeneratedMobileNumberWidget(),
              ),
              Positioned(
                left: 95.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 26.0,
                child: GeneratedNameWidget(),
              ),
              Positioned(
                left: 96.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 38.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 95.0,
                top: 546.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 38.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 99.0,
                top: 661.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 38.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 96.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 26.0,
                child: GeneratedEmailWidget(),
              ),
              Positioned(
                left: 95.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 26.0,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: 98.0,
                top: 519.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 23.0,
                child: GeneratedConfirmPasswordWidget(),
              ),
              Positioned(
                left: -2.0,
                top: 66.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 0.0,
                child: GeneratedArrow1Widget(),
              ),
              Positioned(
                left: 181.0,
                top: 669.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 26.0,
                child: GeneratedRegisterWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 38.0,
                right: null,
                bottom: null,
                width: 48.5,
                height: 39.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 63.0,
                top: 57.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 0.0,
                child: GeneratedArrow2Widget(),
              )
            ]),
      ),
    ));
  }
}
