import 'package:flutter/material.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel26widget/generated/GeneratedCreateNewAccountWidget2.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel26widget/generated/GeneratedSaviorWidget3.dart';

/* Frame Google Pixel 2 - 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGooglePixel26Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 93, 7, 133),
                ),
              ),
              Positioned(
                left: 111.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 192.0,
                height: 94.0,
                child: GeneratedSaviorWidget3(),
              ),
              Positioned(
                left: 69.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 23.0,
                child: GeneratedCreateNewAccountWidget2(),
              )
            ]),
      ),
    ));
  }
}
