import 'package:flutter/material.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel27widget/generated/GeneratedRectangle1Widget2.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel27widget/generated/GeneratedRectangle3Widget2.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel27widget/generated/GeneratedSaviorWidget2.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel27widget/generated/GeneratedCreateNewAccountWidget1.dart';

/* Frame Google Pixel 2 - 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGooglePixel27Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 135, 88, 158),
                ),
              ),
              Positioned(
                left: 111.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 192.0,
                height: 94.0,
                child: GeneratedSaviorWidget2(),
              ),
              Positioned(
                left: 95.0,
                top: 327.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 38.0,
                child: GeneratedRectangle1Widget2(),
              ),
              Positioned(
                left: 95.0,
                top: 404.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 38.0,
                child: GeneratedRectangle3Widget2(),
              ),
              Positioned(
                left: 123.0,
                top: 412.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 23.0,
                child: GeneratedCreateNewAccountWidget1(),
              )
            ]),
      ),
    ));
  }
}
