import 'package:flutter/material.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel24widget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel24widget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel24widget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel24widget/generated/GeneratedNotificationsWidget.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel24widget/generated/GeneratedSafeZoneWidget.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel24widget/generated/GeneratedTerminationWidget.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel24widget/generated/GeneratedInformationWidget1.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel24widget/generated/GeneratedSaviorWidget5.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel24widget/generated/GeneratedSendLocationWidget.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel24widget/generated/GeneratedRectangle7Widget1.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel24widget/generated/GeneratedRedZoneWidget.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel24widget/generated/GeneratedInformationWidget.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel24widget/generated/GeneratedRectangle5Widget1.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel24widget/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel24widget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel24widget/generated/GeneratedRecordingsWidget.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel24widget/generated/GeneratedRectangle8Widget1.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel24widget/generated/GeneratedCallWidget.dart';

/* Frame Google Pixel 2 - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGooglePixel24Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 93, 7, 133),
                ),
              ),
              Positioned(
                left: 40.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 84.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 536.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 84.0,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 246.0,
                top: 282.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 84.0,
                child: GeneratedRectangle11Widget(),
              ),
              Positioned(
                left: 246.0,
                top: 536.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 84.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 282.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 84.0,
                child: GeneratedRectangle5Widget1(),
              ),
              Positioned(
                left: 246.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 84.0,
                child: GeneratedRectangle6Widget1(),
              ),
              Positioned(
                left: 291.0,
                top: 186.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 26.0,
                child: GeneratedCallWidget(),
              ),
              Positioned(
                left: 62.0,
                top: 311.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 23.0,
                child: GeneratedRedZoneWidget(),
              ),
              Positioned(
                left: 52.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 26.0,
                child: GeneratedInformationWidget(),
              ),
              Positioned(
                left: 246.0,
                top: 409.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 84.0,
                child: GeneratedRectangle7Widget1(),
              ),
              Positioned(
                left: 40.0,
                top: 409.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 84.0,
                child: GeneratedRectangle8Widget1(),
              ),
              Positioned(
                left: 51.0,
                top: 186.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 26.0,
                child: GeneratedInformationWidget1(),
              ),
              Positioned(
                left: 256.0,
                top: 568.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 47.0,
                child: GeneratedTerminationWidget(),
              ),
              Positioned(
                left: 43.0,
                top: 436.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 23.0,
                child: GeneratedSendLocationWidget(),
              ),
              Positioned(
                left: 43.0,
                top: 567.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 26.0,
                child: GeneratedNotificationsWidget(),
              ),
              Positioned(
                left: 257.0,
                top: 313.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 23.0,
                child: GeneratedSafeZoneWidget(),
              ),
              Positioned(
                left: 257.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 26.0,
                child: GeneratedRecordingsWidget(),
              ),
              Positioned(
                left: 209.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 192.0,
                height: 94.0,
                child: GeneratedSaviorWidget5(),
              )
            ]),
      ),
    ));
  }
}
