import 'package:flutter/material.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel25widget/generated/GeneratedRectangle1Widget3.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel25widget/generated/GeneratedRectangle1Widget4.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel25widget/generated/GeneratedPasswordWidget1.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel25widget/generated/GeneratedSaviorWidget4.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel25widget/generated/GeneratedLogInWidget1.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel25widget/generated/GeneratedEmailWidget1.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel25widget/generated/GeneratedRectangle3Widget3.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel25widget/generated/GeneratedArrow3Widget.dart';
import 'package:flutterapp/saviorsecurityapp/generatedgooglepixel25widget/generated/GeneratedRectangle3Widget4.dart';

/* Frame Google Pixel 2 - 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGooglePixel25Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 93, 7, 133),
                ),
              ),
              Positioned(
                left: 96.0,
                top: 579.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 38.0,
                child: GeneratedRectangle1Widget3(),
              ),
              Positioned(
                left: 111.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 192.0,
                height: 94.0,
                child: GeneratedSaviorWidget4(),
              ),
              Positioned(
                left: 95.0,
                top: 327.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 38.0,
                child: GeneratedRectangle1Widget4(),
              ),
              Positioned(
                left: 95.0,
                top: 404.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 38.0,
                child: GeneratedRectangle3Widget3(),
              ),
              Positioned(
                left: 174.0,
                top: 587.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 26.0,
                child: GeneratedLogInWidget1(),
              ),
              Positioned(
                left: 96.0,
                top: 374.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 47.0,
                child: GeneratedPasswordWidget1(),
              ),
              Positioned(
                left: 95.0,
                top: 296.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 26.0,
                child: GeneratedEmailWidget1(),
              ),
              Positioned(
                left: 9.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 38.0,
                child: GeneratedRectangle3Widget4(),
              ),
              Positioned(
                left: 71.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 0.0,
                child: GeneratedArrow3Widget(),
              )
            ]),
      ),
    ));
  }
}
